set(_CATKIN_CURRENT_PACKAGE "ur5_platform_description")
set(ur5_platform_description_VERSION "1.2.1")
set(ur5_platform_description_MAINTAINER "neka-nat <nekanat.stock@gmail.com>")
set(ur5_platform_description_PACKAGE_FORMAT "1")
set(ur5_platform_description_BUILD_DEPENDS )
set(ur5_platform_description_BUILD_EXPORT_DEPENDS "urdf" "pr2_description")
set(ur5_platform_description_BUILDTOOL_DEPENDS "catkin")
set(ur5_platform_description_BUILDTOOL_EXPORT_DEPENDS )
set(ur5_platform_description_EXEC_DEPENDS "urdf" "pr2_description")
set(ur5_platform_description_RUN_DEPENDS "urdf" "pr2_description")
set(ur5_platform_description_TEST_DEPENDS )
set(ur5_platform_description_DOC_DEPENDS )
set(ur5_platform_description_URL_WEBSITE "")
set(ur5_platform_description_URL_BUGTRACKER "")
set(ur5_platform_description_URL_REPOSITORY "")
set(ur5_platform_description_DEPRECATED "")