#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/jay/my_ws/devel_isolated/ur_controllers:$CMAKE_PREFIX_PATH"
export LD_LIBRARY_PATH='/home/jay/my_ws/devel_isolated/ur_controllers/lib:/home/jay/my_ws/devel_isolated/ur_client_library/lib:/home/jay/my_ws/devel_isolated/ur_bringup/lib:/home/jay/my_ws/devel_isolated/ur5_platform_moveit_config/lib:/home/jay/my_ws/devel_isolated/ur5_platform_manipulation/lib:/home/jay/my_ws/devel_isolated/ur5_platform_gazebo/lib:/home/jay/my_ws/devel_isolated/ur5_platform_description/lib:/home/jay/my_ws/devel_isolated/si_utils/lib:/home/jay/my_ws/devel_isolated/robotiq_ft_sensor/lib:/home/jay/my_ws/devel_isolated/robotiq_85_msgs/lib:/home/jay/my_ws/devel_isolated/robotiq_85_moveit_config/lib:/home/jay/my_ws/devel_isolated/robotiq_85_gazebo/lib:/home/jay/my_ws/devel_isolated/robotiq_85_driver/lib:/home/jay/my_ws/devel_isolated/robotiq_85_description/lib:/home/jay/my_ws/devel_isolated/robotiq_85_bringup/lib:/home/jay/my_ws/devel_isolated/roboticsgroup_gazebo_plugins/lib:/home/jay/my_ws/devel_isolated/gazebo_grasp_plugin/lib:/home/jay/my_ws/devel_isolated/find_object_2d/lib:/home/jay/my_ws/devel_isolated/controller_stopper/lib:/home/jay/gpd_ws/devel/lib:/home/jay/ork_ws/devel/lib:/home/jay/realsense_ws/devel/lib:/home/jay/my_ws/devel/lib:/home/jay/ur_ws/devel/lib:/home/jay/ros_web_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu'
export PATH='/home/jay/ork_ws/devel/bin:/opt/ros/kinetic/bin:/home/jay/bin:/home/jay/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/jay/my_ws/devel_isolated/ur_controllers/lib/pkgconfig:/home/jay/my_ws/devel_isolated/ur_bringup/lib/pkgconfig:/home/jay/my_ws/devel_isolated/ur5_platform_moveit_config/lib/pkgconfig:/home/jay/my_ws/devel_isolated/ur5_platform_manipulation/lib/pkgconfig:/home/jay/my_ws/devel_isolated/ur5_platform_gazebo/lib/pkgconfig:/home/jay/my_ws/devel_isolated/ur5_platform_description/lib/pkgconfig:/home/jay/my_ws/devel_isolated/si_utils/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_ft_sensor/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_85_msgs/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_85_moveit_config/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_85_gazebo/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_85_driver/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_85_description/lib/pkgconfig:/home/jay/my_ws/devel_isolated/robotiq_85_bringup/lib/pkgconfig:/home/jay/my_ws/devel_isolated/roboticsgroup_gazebo_plugins/lib/pkgconfig:/home/jay/my_ws/devel_isolated/gazebo_grasp_plugin/lib/pkgconfig:/home/jay/my_ws/devel_isolated/find_object_2d/lib/pkgconfig:/home/jay/my_ws/devel_isolated/controller_stopper/lib/pkgconfig:/home/jay/gpd_ws/devel/lib/pkgconfig:/home/jay/ork_ws/devel/lib/pkgconfig:/home/jay/realsense_ws/devel/lib/pkgconfig:/home/jay/my_ws/devel/lib/pkgconfig:/home/jay/ur_ws/devel/lib/pkgconfig:/home/jay/ros_web_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/jay/my_ws/devel_isolated/robotiq_ft_sensor/lib/python2.7/dist-packages:/home/jay/my_ws/devel_isolated/robotiq_85_msgs/lib/python2.7/dist-packages:/home/jay/my_ws/devel_isolated/robotiq_85_driver/lib/python2.7/dist-packages:/home/jay/my_ws/devel_isolated/find_object_2d/lib/python2.7/dist-packages:/home/jay/gpd_ws/devel/lib/python2.7/dist-packages:/home/jay/ork_ws/devel/lib/python2.7/dist-packages:/home/jay/realsense_ws/devel/lib/python2.7/dist-packages:/home/jay/my_ws/devel/lib/python2.7/dist-packages:/home/jay/ur_ws/devel/lib/python2.7/dist-packages:/home/jay/ros_web_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/jay/models/research:/home/jay/models/research/slim'
export ROSLISP_PACKAGE_DIRECTORIES="/home/jay/my_ws/devel_isolated/ur_controllers/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_controllers:/home/jay/my_ws/devel_isolated/ur_client_library/share:$ROS_PACKAGE_PATH"