set(_CATKIN_CURRENT_PACKAGE "ur5_platform_moveit_config")
set(ur5_platform_moveit_config_VERSION "0.3.0")
set(ur5_platform_moveit_config_MAINTAINER "jay <1667248327@qq.com>")
set(ur5_platform_moveit_config_PACKAGE_FORMAT "1")
set(ur5_platform_moveit_config_BUILD_DEPENDS "ur5_platform_description")
set(ur5_platform_moveit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "ur5_platform_description")
set(ur5_platform_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(ur5_platform_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(ur5_platform_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "ur5_platform_description")
set(ur5_platform_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "ur5_platform_description")
set(ur5_platform_moveit_config_TEST_DEPENDS )
set(ur5_platform_moveit_config_DOC_DEPENDS )
set(ur5_platform_moveit_config_URL_WEBSITE "http://moveit.ros.org/")
set(ur5_platform_moveit_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(ur5_platform_moveit_config_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(ur5_platform_moveit_config_DEPRECATED "")