// Generated by gencpp from file easy_handeye_msgs/CheckStartingPose.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_CHECKSTARTINGPOSE_H
#define EASY_HANDEYE_MSGS_MESSAGE_CHECKSTARTINGPOSE_H

#include <ros/service_traits.h>


#include <easy_handeye_msgs/CheckStartingPoseRequest.h>
#include <easy_handeye_msgs/CheckStartingPoseResponse.h>


namespace easy_handeye_msgs
{

struct CheckStartingPose
{

typedef CheckStartingPoseRequest Request;
typedef CheckStartingPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckStartingPose
} // namespace easy_handeye_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye_msgs::CheckStartingPose > {
  static const char* value()
  {
    return "2e21f20435619eabca85520d8feb5839";
  }

  static const char* value(const ::easy_handeye_msgs::CheckStartingPose&) { return value(); }
};

template<>
struct DataType< ::easy_handeye_msgs::CheckStartingPose > {
  static const char* value()
  {
    return "easy_handeye_msgs/CheckStartingPose";
  }

  static const char* value(const ::easy_handeye_msgs::CheckStartingPose&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye_msgs::CheckStartingPoseRequest> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::CheckStartingPose > 
template<>
struct MD5Sum< ::easy_handeye_msgs::CheckStartingPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::CheckStartingPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::CheckStartingPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::CheckStartingPoseRequest> should match 
// service_traits::DataType< ::easy_handeye_msgs::CheckStartingPose > 
template<>
struct DataType< ::easy_handeye_msgs::CheckStartingPoseRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::CheckStartingPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::CheckStartingPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye_msgs::CheckStartingPoseResponse> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::CheckStartingPose > 
template<>
struct MD5Sum< ::easy_handeye_msgs::CheckStartingPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::CheckStartingPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::CheckStartingPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::CheckStartingPoseResponse> should match 
// service_traits::DataType< ::easy_handeye_msgs::CheckStartingPose > 
template<>
struct DataType< ::easy_handeye_msgs::CheckStartingPoseResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::CheckStartingPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::CheckStartingPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_CHECKSTARTINGPOSE_H
