// Generated by gencpp from file easy_handeye_msgs/EnumerateTargetPoses.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_ENUMERATETARGETPOSES_H
#define EASY_HANDEYE_MSGS_MESSAGE_ENUMERATETARGETPOSES_H

#include <ros/service_traits.h>


#include <easy_handeye_msgs/EnumerateTargetPosesRequest.h>
#include <easy_handeye_msgs/EnumerateTargetPosesResponse.h>


namespace easy_handeye_msgs
{

struct EnumerateTargetPoses
{

typedef EnumerateTargetPosesRequest Request;
typedef EnumerateTargetPosesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnumerateTargetPoses
} // namespace easy_handeye_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye_msgs::EnumerateTargetPoses > {
  static const char* value()
  {
    return "80d5a3ee3a473035f3acfbf477197597";
  }

  static const char* value(const ::easy_handeye_msgs::EnumerateTargetPoses&) { return value(); }
};

template<>
struct DataType< ::easy_handeye_msgs::EnumerateTargetPoses > {
  static const char* value()
  {
    return "easy_handeye_msgs/EnumerateTargetPoses";
  }

  static const char* value(const ::easy_handeye_msgs::EnumerateTargetPoses&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye_msgs::EnumerateTargetPosesRequest> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::EnumerateTargetPoses > 
template<>
struct MD5Sum< ::easy_handeye_msgs::EnumerateTargetPosesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::EnumerateTargetPoses >::value();
  }
  static const char* value(const ::easy_handeye_msgs::EnumerateTargetPosesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::EnumerateTargetPosesRequest> should match 
// service_traits::DataType< ::easy_handeye_msgs::EnumerateTargetPoses > 
template<>
struct DataType< ::easy_handeye_msgs::EnumerateTargetPosesRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::EnumerateTargetPoses >::value();
  }
  static const char* value(const ::easy_handeye_msgs::EnumerateTargetPosesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye_msgs::EnumerateTargetPosesResponse> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::EnumerateTargetPoses > 
template<>
struct MD5Sum< ::easy_handeye_msgs::EnumerateTargetPosesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::EnumerateTargetPoses >::value();
  }
  static const char* value(const ::easy_handeye_msgs::EnumerateTargetPosesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::EnumerateTargetPosesResponse> should match 
// service_traits::DataType< ::easy_handeye_msgs::EnumerateTargetPoses > 
template<>
struct DataType< ::easy_handeye_msgs::EnumerateTargetPosesResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::EnumerateTargetPoses >::value();
  }
  static const char* value(const ::easy_handeye_msgs::EnumerateTargetPosesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_ENUMERATETARGETPOSES_H
