// Generated by gencpp from file easy_handeye_msgs/ListAlgorithms.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_LISTALGORITHMS_H
#define EASY_HANDEYE_MSGS_MESSAGE_LISTALGORITHMS_H

#include <ros/service_traits.h>


#include <easy_handeye_msgs/ListAlgorithmsRequest.h>
#include <easy_handeye_msgs/ListAlgorithmsResponse.h>


namespace easy_handeye_msgs
{

struct ListAlgorithms
{

typedef ListAlgorithmsRequest Request;
typedef ListAlgorithmsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListAlgorithms
} // namespace easy_handeye_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye_msgs::ListAlgorithms > {
  static const char* value()
  {
    return "cf0f5784afc7ca3b01a2029aa7874966";
  }

  static const char* value(const ::easy_handeye_msgs::ListAlgorithms&) { return value(); }
};

template<>
struct DataType< ::easy_handeye_msgs::ListAlgorithms > {
  static const char* value()
  {
    return "easy_handeye_msgs/ListAlgorithms";
  }

  static const char* value(const ::easy_handeye_msgs::ListAlgorithms&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye_msgs::ListAlgorithmsRequest> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::ListAlgorithms > 
template<>
struct MD5Sum< ::easy_handeye_msgs::ListAlgorithmsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::ListAlgorithms >::value();
  }
  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::ListAlgorithmsRequest> should match 
// service_traits::DataType< ::easy_handeye_msgs::ListAlgorithms > 
template<>
struct DataType< ::easy_handeye_msgs::ListAlgorithmsRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::ListAlgorithms >::value();
  }
  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye_msgs::ListAlgorithmsResponse> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::ListAlgorithms > 
template<>
struct MD5Sum< ::easy_handeye_msgs::ListAlgorithmsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::ListAlgorithms >::value();
  }
  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::ListAlgorithmsResponse> should match 
// service_traits::DataType< ::easy_handeye_msgs::ListAlgorithms > 
template<>
struct DataType< ::easy_handeye_msgs::ListAlgorithmsResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::ListAlgorithms >::value();
  }
  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_LISTALGORITHMS_H
