// Generated by gencpp from file easy_handeye_msgs/ListAlgorithmsResponse.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_LISTALGORITHMSRESPONSE_H
#define EASY_HANDEYE_MSGS_MESSAGE_LISTALGORITHMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace easy_handeye_msgs
{
template <class ContainerAllocator>
struct ListAlgorithmsResponse_
{
  typedef ListAlgorithmsResponse_<ContainerAllocator> Type;

  ListAlgorithmsResponse_()
    : algorithms()
    , current_algorithm()  {
    }
  ListAlgorithmsResponse_(const ContainerAllocator& _alloc)
    : algorithms(_alloc)
    , current_algorithm(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _algorithms_type;
  _algorithms_type algorithms;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _current_algorithm_type;
  _current_algorithm_type current_algorithm;





  typedef boost::shared_ptr< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListAlgorithmsResponse_

typedef ::easy_handeye_msgs::ListAlgorithmsResponse_<std::allocator<void> > ListAlgorithmsResponse;

typedef boost::shared_ptr< ::easy_handeye_msgs::ListAlgorithmsResponse > ListAlgorithmsResponsePtr;
typedef boost::shared_ptr< ::easy_handeye_msgs::ListAlgorithmsResponse const> ListAlgorithmsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace easy_handeye_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'easy_handeye_msgs': ['/home/jay/my_ws/src/easy_handeye/easy_handeye_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf0f5784afc7ca3b01a2029aa7874966";
  }

  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf0f5784afc7ca3bULL;
  static const uint64_t static_value2 = 0x01a2029aa7874966ULL;
};

template<class ContainerAllocator>
struct DataType< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "easy_handeye_msgs/ListAlgorithmsResponse";
  }

  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] algorithms\n\
string current_algorithm\n\
";
  }

  static const char* value(const ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.algorithms);
      stream.next(m.current_algorithm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListAlgorithmsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::easy_handeye_msgs::ListAlgorithmsResponse_<ContainerAllocator>& v)
  {
    s << indent << "algorithms[]" << std::endl;
    for (size_t i = 0; i < v.algorithms.size(); ++i)
    {
      s << indent << "  algorithms[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.algorithms[i]);
    }
    s << indent << "current_algorithm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.current_algorithm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_LISTALGORITHMSRESPONSE_H
