// Generated by gencpp from file easy_handeye_msgs/RemoveSample.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_REMOVESAMPLE_H
#define EASY_HANDEYE_MSGS_MESSAGE_REMOVESAMPLE_H

#include <ros/service_traits.h>


#include <easy_handeye_msgs/RemoveSampleRequest.h>
#include <easy_handeye_msgs/RemoveSampleResponse.h>


namespace easy_handeye_msgs
{

struct RemoveSample
{

typedef RemoveSampleRequest Request;
typedef RemoveSampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveSample
} // namespace easy_handeye_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye_msgs::RemoveSample > {
  static const char* value()
  {
    return "c70c6764515bed995cb2d85181cfefb3";
  }

  static const char* value(const ::easy_handeye_msgs::RemoveSample&) { return value(); }
};

template<>
struct DataType< ::easy_handeye_msgs::RemoveSample > {
  static const char* value()
  {
    return "easy_handeye_msgs/RemoveSample";
  }

  static const char* value(const ::easy_handeye_msgs::RemoveSample&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye_msgs::RemoveSampleRequest> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::RemoveSample > 
template<>
struct MD5Sum< ::easy_handeye_msgs::RemoveSampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::RemoveSampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::RemoveSampleRequest> should match 
// service_traits::DataType< ::easy_handeye_msgs::RemoveSample > 
template<>
struct DataType< ::easy_handeye_msgs::RemoveSampleRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::RemoveSampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye_msgs::RemoveSampleResponse> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::RemoveSample > 
template<>
struct MD5Sum< ::easy_handeye_msgs::RemoveSampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::RemoveSampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::RemoveSampleResponse> should match 
// service_traits::DataType< ::easy_handeye_msgs::RemoveSample > 
template<>
struct DataType< ::easy_handeye_msgs::RemoveSampleResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::RemoveSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::RemoveSampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_REMOVESAMPLE_H
