// Generated by gencpp from file easy_handeye_msgs/SelectTargetPose.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_SELECTTARGETPOSE_H
#define EASY_HANDEYE_MSGS_MESSAGE_SELECTTARGETPOSE_H

#include <ros/service_traits.h>


#include <easy_handeye_msgs/SelectTargetPoseRequest.h>
#include <easy_handeye_msgs/SelectTargetPoseResponse.h>


namespace easy_handeye_msgs
{

struct SelectTargetPose
{

typedef SelectTargetPoseRequest Request;
typedef SelectTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SelectTargetPose
} // namespace easy_handeye_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye_msgs::SelectTargetPose > {
  static const char* value()
  {
    return "7b5a90234960b4a47b29711a1572dab1";
  }

  static const char* value(const ::easy_handeye_msgs::SelectTargetPose&) { return value(); }
};

template<>
struct DataType< ::easy_handeye_msgs::SelectTargetPose > {
  static const char* value()
  {
    return "easy_handeye_msgs/SelectTargetPose";
  }

  static const char* value(const ::easy_handeye_msgs::SelectTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye_msgs::SelectTargetPoseRequest> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::SelectTargetPose > 
template<>
struct MD5Sum< ::easy_handeye_msgs::SelectTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::SelectTargetPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::SelectTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::SelectTargetPoseRequest> should match 
// service_traits::DataType< ::easy_handeye_msgs::SelectTargetPose > 
template<>
struct DataType< ::easy_handeye_msgs::SelectTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::SelectTargetPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::SelectTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye_msgs::SelectTargetPoseResponse> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::SelectTargetPose > 
template<>
struct MD5Sum< ::easy_handeye_msgs::SelectTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::SelectTargetPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::SelectTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::SelectTargetPoseResponse> should match 
// service_traits::DataType< ::easy_handeye_msgs::SelectTargetPose > 
template<>
struct DataType< ::easy_handeye_msgs::SelectTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::SelectTargetPose >::value();
  }
  static const char* value(const ::easy_handeye_msgs::SelectTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_SELECTTARGETPOSE_H
