// Generated by gencpp from file easy_handeye_msgs/TakeSample.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_TAKESAMPLE_H
#define EASY_HANDEYE_MSGS_MESSAGE_TAKESAMPLE_H

#include <ros/service_traits.h>


#include <easy_handeye_msgs/TakeSampleRequest.h>
#include <easy_handeye_msgs/TakeSampleResponse.h>


namespace easy_handeye_msgs
{

struct TakeSample
{

typedef TakeSampleRequest Request;
typedef TakeSampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeSample
} // namespace easy_handeye_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::easy_handeye_msgs::TakeSample > {
  static const char* value()
  {
    return "7d95fb9676bbeca74481a1f545ed96b0";
  }

  static const char* value(const ::easy_handeye_msgs::TakeSample&) { return value(); }
};

template<>
struct DataType< ::easy_handeye_msgs::TakeSample > {
  static const char* value()
  {
    return "easy_handeye_msgs/TakeSample";
  }

  static const char* value(const ::easy_handeye_msgs::TakeSample&) { return value(); }
};


// service_traits::MD5Sum< ::easy_handeye_msgs::TakeSampleRequest> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::TakeSample > 
template<>
struct MD5Sum< ::easy_handeye_msgs::TakeSampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::TakeSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::TakeSampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::TakeSampleRequest> should match 
// service_traits::DataType< ::easy_handeye_msgs::TakeSample > 
template<>
struct DataType< ::easy_handeye_msgs::TakeSampleRequest>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::TakeSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::TakeSampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::easy_handeye_msgs::TakeSampleResponse> should match 
// service_traits::MD5Sum< ::easy_handeye_msgs::TakeSample > 
template<>
struct MD5Sum< ::easy_handeye_msgs::TakeSampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::easy_handeye_msgs::TakeSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::TakeSampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::easy_handeye_msgs::TakeSampleResponse> should match 
// service_traits::DataType< ::easy_handeye_msgs::TakeSample > 
template<>
struct DataType< ::easy_handeye_msgs::TakeSampleResponse>
{
  static const char* value()
  {
    return DataType< ::easy_handeye_msgs::TakeSample >::value();
  }
  static const char* value(const ::easy_handeye_msgs::TakeSampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_TAKESAMPLE_H
