// Generated by gencpp from file easy_handeye_msgs/TargetPoseList.msg
// DO NOT EDIT!


#ifndef EASY_HANDEYE_MSGS_MESSAGE_TARGETPOSELIST_H
#define EASY_HANDEYE_MSGS_MESSAGE_TARGETPOSELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace easy_handeye_msgs
{
template <class ContainerAllocator>
struct TargetPoseList_
{
  typedef TargetPoseList_<ContainerAllocator> Type;

  TargetPoseList_()
    : home_pose()
    , target_poses()
    , current_target_pose_index(0)  {
    }
  TargetPoseList_(const ContainerAllocator& _alloc)
    : home_pose(_alloc)
    , target_poses(_alloc)
    , current_target_pose_index(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _home_pose_type;
  _home_pose_type home_pose;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _target_poses_type;
  _target_poses_type target_poses;

   typedef int64_t _current_target_pose_index_type;
  _current_target_pose_index_type current_target_pose_index;





  typedef boost::shared_ptr< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> const> ConstPtr;

}; // struct TargetPoseList_

typedef ::easy_handeye_msgs::TargetPoseList_<std::allocator<void> > TargetPoseList;

typedef boost::shared_ptr< ::easy_handeye_msgs::TargetPoseList > TargetPoseListPtr;
typedef boost::shared_ptr< ::easy_handeye_msgs::TargetPoseList const> TargetPoseListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace easy_handeye_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'easy_handeye_msgs': ['/home/jay/my_ws/src/easy_handeye/easy_handeye_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c343b905aff6f17d2d7f55ae6eecc3c";
  }

  static const char* value(const ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c343b905aff6f17ULL;
  static const uint64_t static_value2 = 0xd2d7f55ae6eecc3cULL;
};

template<class ContainerAllocator>
struct DataType< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "easy_handeye_msgs/TargetPoseList";
  }

  static const char* value(const ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped home_pose\n\
geometry_msgs/PoseStamped[] target_poses\n\
int64 current_target_pose_index\n\
# TODO: add joint poses (which are what will actually be used)\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.home_pose);
      stream.next(m.target_poses);
      stream.next(m.current_target_pose_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetPoseList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::easy_handeye_msgs::TargetPoseList_<ContainerAllocator>& v)
  {
    s << indent << "home_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.home_pose);
    s << indent << "target_poses[]" << std::endl;
    for (size_t i = 0; i < v.target_poses.size(); ++i)
    {
      s << indent << "  target_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.target_poses[i]);
    }
    s << indent << "current_target_pose_index: ";
    Printer<int64_t>::stream(s, indent + "  ", v.current_target_pose_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EASY_HANDEYE_MSGS_MESSAGE_TARGETPOSELIST_H
