# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/msg/ProgramState.msg;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/msg/RobotMode.msg;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/msg/SafetyMode.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeAction.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeActionGoal.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeActionResult.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeActionFeedback.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeGoal.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeResult.msg;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg/SetModeFeedback.msg"
services_str = "/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/AddToLog.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/GetLoadedProgram.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/GetProgramState.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/GetRobotMode.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/GetSafetyMode.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/IsProgramRunning.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/IsProgramSaved.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/Load.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/Popup.srv;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/srv/RawRequest.srv"
pkg_name = "ur_dashboard_msgs"
dependencies_str = "std_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "ur_dashboard_msgs;/home/jay/my_ws/src/Universal_Robots_ROS_Driver/ur_dashboard_msgs/msg;ur_dashboard_msgs;/home/jay/my_ws/devel_isolated/ur_dashboard_msgs/share/ur_dashboard_msgs/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;actionlib_msgs;/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
