// Generated by gencpp from file ur_msgs/SetPayloadRequest.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_SETPAYLOADREQUEST_H
#define UR_MSGS_MESSAGE_SETPAYLOADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace ur_msgs
{
template <class ContainerAllocator>
struct SetPayloadRequest_
{
  typedef SetPayloadRequest_<ContainerAllocator> Type;

  SetPayloadRequest_()
    : payload(0.0)
    , center_of_gravity()  {
    }
  SetPayloadRequest_(const ContainerAllocator& _alloc)
    : payload(0.0)
    , center_of_gravity(_alloc)  {
  (void)_alloc;
    }



   typedef float _payload_type;
  _payload_type payload;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _center_of_gravity_type;
  _center_of_gravity_type center_of_gravity;





  typedef boost::shared_ptr< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPayloadRequest_

typedef ::ur_msgs::SetPayloadRequest_<std::allocator<void> > SetPayloadRequest;

typedef boost::shared_ptr< ::ur_msgs::SetPayloadRequest > SetPayloadRequestPtr;
typedef boost::shared_ptr< ::ur_msgs::SetPayloadRequest const> SetPayloadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::SetPayloadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ur_msgs': ['/home/jay/my_ws/src/fmauch_universal_robot/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb05883ed2c985331004a717cd96a56";
  }

  static const char* value(const ::ur_msgs::SetPayloadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb05883ed2c9853ULL;
  static const uint64_t static_value2 = 0x31004a717cd96a56ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/SetPayloadRequest";
  }

  static const char* value(const ::ur_msgs::SetPayloadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 payload\n\
geometry_msgs/Vector3 center_of_gravity\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ur_msgs::SetPayloadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.payload);
      stream.next(m.center_of_gravity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPayloadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::SetPayloadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_msgs::SetPayloadRequest_<ContainerAllocator>& v)
  {
    s << indent << "payload: ";
    Printer<float>::stream(s, indent + "  ", v.payload);
    s << indent << "center_of_gravity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.center_of_gravity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_SETPAYLOADREQUEST_H
